"use client"
import './globals.css'
import AOS from 'aos';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useEffect } from 'react';
import 'aos/dist/aos.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Geeks Inventionyy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    AOS.init();
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
